// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8pOIn2TFtFrMR9FlsqbOXOcgOWu6SmY',
    appId: '1:835561269321:web:b10cf0d9e3ae554b223798',
    messagingSenderId: '835561269321',
    projectId: 'carservices-fd6b2',
    authDomain: 'carservices-fd6b2.firebaseapp.com',
    storageBucket: 'carservices-fd6b2.appspot.com',
    measurementId: 'G-P4MP8QPZH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9YmVZPBRtKkbYrGIKcNSi4LzuoOxWoY',
    appId: '1:835561269321:android:984a0ee6b1ba0335223798',
    messagingSenderId: '835561269321',
    projectId: 'carservices-fd6b2',
    storageBucket: 'carservices-fd6b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABpzs1uSRoWKsbQ_TQGBgEAx1X9K8mMW0',
    appId: '1:835561269321:ios:4fb40b5b313e77f7223798',
    messagingSenderId: '835561269321',
    projectId: 'carservices-fd6b2',
    storageBucket: 'carservices-fd6b2.appspot.com',
    iosClientId: '835561269321-o666i5o10bt8gqc61db381sn92blod95.apps.googleusercontent.com',
    iosBundleId: 'com.example.carServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABpzs1uSRoWKsbQ_TQGBgEAx1X9K8mMW0',
    appId: '1:835561269321:ios:4fb40b5b313e77f7223798',
    messagingSenderId: '835561269321',
    projectId: 'carservices-fd6b2',
    storageBucket: 'carservices-fd6b2.appspot.com',
    iosClientId: '835561269321-o666i5o10bt8gqc61db381sn92blod95.apps.googleusercontent.com',
    iosBundleId: 'com.example.carServices',
  );
}
